# Healthcare EDA Project

This notebook covers:
- Loading & combining datasets
- Data cleaning
- Exploratory Data Analysis (EDA)
- Filtering, GroupBy, Transformations
- Advanced analysis
- Final export

> Files expected in the same folder:
- patient_master_1.csv
- patient_master_2.csv

In [10]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

## 1) Load & Combine Data

In [11]:
#Load the patient master CSV file into a Pandas DataFrame 
#📝 Note: Use pd.read_csv() and store it in a DataFrame variable. Make sure the file path is correct. 

df1 = pd.read_csv(r"patient_master_1.csv")
df2 = pd.read_csv(r"patient_master_2.csv")

df = pd.concat([df1, df2])
df = df.reset_index(drop=True)

df.shape

(160000, 25)

## 2) Basic Exploration (Q1–15)

In [12]:
#Display the first 5 rows of the dataset 
#📝 Note: This helps you quickly understand column names,data format, and sample values. 

df.head()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,Address,City,State,Country,Pincode,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,Local Address,Navi Mumbai,Maharashtra,India,400271,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,Local Address,Mumbai,Maharashtra,India,401660,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,Local Address,Nashik,Maharashtra,India,409094,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,Local Address,Mumbai,Maharashtra,India,402003,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,Local Address,Navi Mumbai,Maharashtra,India,403090,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04

In [13]:
#Display the last 5 rows of the dataset 
#📝 Note: Useful to verify the ending records and check data completeness. 

df.tail()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,Address,City,State,Country,Pincode,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
159995,P159996,Arjun,Patil,Female,60,1965-04-21,B+,Married,9630982227,user159996@mail.com,Local Address,Kolhapur,Maharashtra,India,404215,184,70,20.7,Yes,No,Thyroid,D102,Reliance General,POL340217,2021-09-02
159996,P159997,Priya,Verma,Female,53,1972-07-09,B+,Married,9309689795,user159997@mail.com,Local Address,Mumbai,Maharashtra,India,400478,171,54,18.5,Yes,No,Cardiac,D103,New India Assurance,POL440488,2021-03-09
159997,P159998,Priya,Gupta,Male,59,1966-11-27,B+,Single,9493413949,user159998@mail.com,Local Address,Aurangabad,Maharashtra,India,400769,181,59,18.0,Yes,No,NaN,D100,ICICI Lombard,POL964388,2021-01-20
159998,P159999,Neha,Mehta,Female,27,1998-08-14,A-,Married,9988283820,user159999@mail.com,Local Address,Nagpur,Maharashtra,India,409443,157,82,33.3,No,No,Hypertension,D109,New India Assurance,POL246218,2021-02-07
159999,P160000,Kavita,Sharma,Male,31,1994-09-09,A+,Married,9907216968,user160000@mail.com,Local Address,Kolhapur,Maharashtra,India,406094,183,59,17.6,Yes,No,Hypertension,D112,Bajaj Allianz,POL102734,2020-10-01

In [14]:
#Find the total number of rows and columns 
#📝 Note: Output should be in the form (rows, columns).
    
print(df.shape)

#Display column names 
#📝 Note: Helps identify exact column names to avoid spelling mistakes later. 
    
print(df.columns)

#Display data types of all columns 
#📝 Note: Verify whether numeric columns are stored as int/float and dates as object/datetime. 

print(df.dtypes)

(160000, 25)
Index(['Patient_ID', 'First_Name', 'Last_Name', 'Gender', 'Age',
       'Date_of_Birth', 'Blood_Group', 'Marital_Status', 'Phone_Number',
       'Email', 'Address', 'City', 'State', 'Country', 'Pincode', 'Height_cm',
       'Weight_kg', 'BMI', 'Smoking_Status', 'Alcohol_Consumption',
       'Chronic_Condition', 'Primary_Doctor_ID', 'Insurance_Provider',
       'Insurance_Policy_No', 'Registration_Date'],
      dtype='str')
Patient_ID                 str
First_Name                 str
Last_Name                  str
Gender                     str
Age                      int64
Date_of_Birth              str
Blood_Group                str
Marital_Status             str
Phone_Number             int64
Email                      str
Address                    str
City                       str
State                      str
Country                    str
Pincode                  int64
Height_cm                int64
Weight_kg                int64
BMI                    float64
Smoking_Status             str
Alcohol_Consumption        str
Chronic_Condition          str
Primary_Doctor_ID          str
Insurance_Provider         str
Insurance_Policy_No        str
Registration_Date          str
dtype: object

In [15]:
#Show summary statistics for numerical columns 
#📝 Note: Includes count, mean, min, max, and standard deviation. 
    
df.describe()
    
#Show summary statistics for all columns 
#📝 Note: Includes categorical stats like unique values and most frequent value. 

df.describe(include='all')

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,Address,City,State,Country,Pincode,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
count,160000,160000,160000,160000,160000.000000,160000,160000,160000,1.600000e+05,160000,160000,160000,160000,160000,160000.000000,160000.000000,160000.000000,160000.000000,160000,160000,132695,160000,160000,160000,160000
unique,160000,12,11,2,NaN,15001,8,2,NaN,160000,1,7,1,1,NaN,NaN,NaN,NaN,2,2,5,21,6,146773,1801
top,P00001,Suresh,Joshi,Male,NaN,1987-10-02,B-,Single,NaN,user1@mail.com,Local Address,Nagpur,Maharashtra,India,NaN,NaN,NaN,NaN,No,Occasionally,Asthma,D105,Star Health,POL962909,2023-05-21
freq,1,13851,14827,80223,NaN,28,20244,80202,NaN,1,160000,24079,160000,160000,NaN,NaN,NaN,NaN,80052,80380,27319,8625,27537,4,129
mean,NaN,NaN,NaN,NaN,45.029387,NaN,NaN,NaN,9.500040e+09,NaN,NaN,NaN,NaN,NaN,405560.320562,167.137419,71.356737,25.830098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,11.613874,NaN,NaN,NaN,2.889192e+08,NaN,NaN,NaN,NaN,NaN,3204.713586,10.234342,13.623075,5.881303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,9.000007e+09,NaN,NaN,NaN,NaN,NaN,400001.000000,150.000000,48.000000,14.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,35.000000,NaN,NaN,NaN,9.249921e+09,NaN,NaN,NaN,NaN,NaN,402787.000000,158.000000,60.000000,21.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,45.000000,NaN,NaN,NaN,9.499822e+09,NaN,NaN,NaN,NaN,NaN,405562.000000,167.000000,71.000000,25.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,9.750625e+09,NaN,NaN,NaN,NaN,NaN,408335.000000,176.000000,83.000000,29.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,66.000000,NaN,NaN,NaN,9.999998e+09,NaN,NaN,NaN,NaN,NaN,411099.000000,185.000000,95.000000,42.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Check how many missing values exist per column 
#📝 Note: Identify columns that need data cleaning or filling. 
    
df.isnull().sum()

Patient_ID                 0
First_Name                 0
Last_Name                  0
Gender                     0
Age                        0
Date_of_Birth              0
Blood_Group                0
Marital_Status             0
Phone_Number               0
Email                      0
Address                    0
City                       0
State                      0
Country                    0
Pincode                    0
Height_cm                  0
Weight_kg                  0
BMI                        0
Smoking_Status             0
Alcohol_Consumption        0
Chronic_Condition      27305
Primary_Doctor_ID          0
Insurance_Provider         0
Insurance_Policy_No        0
Registration_Date          0
dtype: int64

In [17]:
#Check if the dataset contains duplicate Patient_IDs 
#📝 Note: Patient_ID should be unique; duplicates indicate data quality issues. 

if 'Patient_ID' in df.columns:
    print('Duplicate Patient_ID:', df['Patient_ID'].duplicated().sum())

#Find the total number of unique patients 
#📝 Note: Use Patient_ID to verify uniqueness.

    print('Unique patients:', df['Patient_ID'].nunique())

Duplicate Patient_ID: 0
Unique patients: 160000

In [18]:
# Display memory usage of the DataFrame 
#📝 Note: Important when working with large healthcare datasets. 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 160000 entries, 0 to 159999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Patient_ID           160000 non-null  str
 1   First_Name           160000 non-null  str
 2   Last_Name            160000 non-null  str
 3   Gender               160000 non-null  str
 4   Age                  160000 non-null  int64
 5   Date_of_Birth        160000 non-null  str
 6   Blood_Group          160000 non-null  str
 7   Marital_Status       160000 non-null  str
 8   Phone_Number         160000 non-null  int64
 9   Email                160000 non-null  str
 10  Address              160000 non-null  str
 11  City                 160000 non-null  str
 12  State                160000 non-null  str
 13  Country              160000 non-null  str
 14  Pincode              160000 non-null  int64
 15  Height_cm            160000 non-null  int64
 16  Weight_kg            160000 non-null  int64
 17  BMI                  160000 non-null  float64
 18  Smoking_Status       160000 non-null  str
 19  Alcohol_Consumption  160000 non-null  str
 20  Chronic_Condition    132695 non-null  str
 21  Primary_Doctor_ID    160000 non-null  str
 22  Insurance_Provider   160000 non-null  str
 23  Insurance_Policy_No  160000 non-null  str
 24  Registration_Date    160000 non-null  str
dtypes: float64(1), int64(5), str(19)
memory usage: 30.5 MB

In [79]:
#Sort patients by Age in descending order 
#📝 Note: Oldest patients should appear first. 

if 'Age' in df.columns:
    df.sort_values(by='Age', ascending=False).head()

In [80]:
#Sort patients by Registration_Date in ascending order 
#📝 Note: Earliest registered patients should appear first. 

if 'Registration_Date' in df.columns:
    # will convert later
    pass

In [81]:
#Display random 10 patient records 
#📝 Note: Random sampling helps quick data inspection. 

df.sample(10)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,City,State,Country,Pincode,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Year,Age_Group,Risk_Level,Reg_Year,Reg_Month,Is_Senior,High_Risk,Insurance_Status,Patient_Location
63465,P33829,Suresh,Nair,Female,49,1976-03-09,B-,Single,9717578297,Local Address,Pune,Maharashtra,India,409847,158,68,27.2,No,Occasionally,Asthma,D101,ICICI Lombard,POL537923,2021-04-30,2021,Adult,Medium,2021,4,False,False,Yes,"Pune, Maharashtra"
152994,P130333,Rahul,Patil,Female,48,1977-03-28,AB+,Married,9834399204,Local Address,Nagpur,Maharashtra,India,406532,173,50,16.7,Yes,No,Unknown,D106,Reliance General,POL510517,2021-09-26,2021,Adult,Low,2021,9,False,False,Yes,"Nagpur, Maharashtra"
151636,P36952,Neha,Mehta,Male,51,1974-12-18,O-,Single,9740612507,Local Address,Kolhapur,Maharashtra,India,406741,180,55,17.0,No,Occasionally,Asthma,D120,ICICI Lombard,POL624144,2020-08-06,2020,Senior,Low,2020,8,False,False,Yes,"Kolhapur, Maharashtra"
98868,P104916,Vikas,Nair,Female,29,1996-10-28,AB-,Single,9925086175,Local Address,Nagpur,Maharashtra,India,408670,182,78,23.5,No,No,Cardiac,D103,ICICI Lombard,POL213923,2021-12-06,2021,Adult,Normal,2021,12,False,False,Yes,"Nagpur, Maharashtra"
60944,P37453,Priya,Singh,Female,60,1965-11-15,A-,Married,9653237734,Local Address,Nashik,Maharashtra,India,410782,179,88,27.5,Yes,No,Cardiac,D115,Reliance General,POL147359,2021-06-11,2021,Senior,Medium,2021,6,False,False,Yes,"Nashik, Maharashtra"
131083,P84059,Anjali,Kulkarni,Male,60,1965-04-11,A-,Single,9769113897,Local Address,Nagpur,Maharashtra,India,405716,158,50,20.0,Yes,Occasionally,Thyroid,D118,ICICI Lombard,POL660383,2021-03-26,2021,Senior,Normal,2021,3,False,False,Yes,"Nagpur, Maharashtra"
19520,P29757,Vikas,Kulkarni,Female,63,1962-09-24,A+,Married,9994676262,Local Address,Nashik,Maharashtra,India,403786,168,94,33.3,No,No,Unknown,D107,Bajaj Allianz,POL125067,2024-02-20,2024,Senior,High,2024,2,True,True,Yes,"Nashik, Maharashtra"
99335,P07719,Suresh,Iyer,Male,29,1996-08-30,O+,Married,9498197622,Local Address,Pune,Maharashtra,India,408600,157,58,23.5,No,Occasionally,Unknown,D104,Star Health,POL546262,2021-03-02,2021,Adult,Normal,2021,3,False,False,Yes,"Pune, Maharashtra"
20566,P28988,Suresh,Gupta,Male,45,1980-01-31,O+,Married,9174202923,Local Address,Pune,Maharashtra,India,408984,168,93,33.0,No,No,Hypertension,D110,Reliance General,POL543607,2023-02-28,2023,Adult,High,2023,2,False,True,Yes,"Pune, Maharashtra"
4124,P01428,Anjali,Gupta,Female,35,1990-07-01,A-,Married,9839882372,Local Address,Navi Mumbai,Maharashtra,India,409345,153,89,38.0,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL300802,2024-01-13,2024,Adult,High,2024,1,False,True,Yes,"Navi Mumbai, Maharashtra"

## 3) Cleaning

In [82]:
# Fill missing


df.fillna('Unknown', inplace=True)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,City,State,Country,Pincode,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Year,Age_Group,Risk_Level,Reg_Year,Reg_Month,Is_Senior,High_Risk,Insurance_Status,Patient_Location
0,P53883,Rohan,Kulkarni,Female,63,1962-06-21,A+,Married,9381946425,Local Address,Nagpur,Maharashtra,India,407831,150,95,42.2,Yes,Occasionally,Unknown,D103,HDFC Ergo,POL198675,2020-10-21,2020,Senior,High,2020,10,True,True,Yes,"Nagpur, Maharashtra"
1,P53825,Rohan,Verma,Female,53,1972-08-11,A+,Single,9421908467,Local Address,Aurangabad,Maharashtra,India,402050,150,95,42.2,No,No,Asthma,D106,New India Assurance,POL921539,2020-11-06,2020,Senior,High,2020,11,False,True,Yes,"Aurangabad, Maharashtra"
2,P108665,Arjun,Joshi,Male,33,1992-11-25,B+,Married,9945809524,Local Address,Nagpur,Maharashtra,India,400369,150,95,42.2,Yes,Occasionally,Diabetes,D115,New India Assurance,POL442020,2020-08-04,2020,Adult,High,2020,8,False,True,Yes,"Nagpur, Maharashtra"
3,P137458,Amit,Patil,Female,54,1971-09-30,O-,Single,9819703121,Local Address,Navi Mumbai,Maharashtra,India,409252,150,95,42.2,No,Occasionally,Diabetes,D102,Star Health,POL587427,2021-12-19,2021,Senior,High,2021,12,False,True,Yes,"Navi Mumbai, Maharashtra"
4,P122760,Arjun,Mehta,Female,55,1970-05-20,O+,Single,9806553943,Local Address,Kolhapur,Maharashtra,India,402839,150,95,42.2,No,No,Unknown,D116,Reliance General,POL795441,2022-10-22,2022,Senior,High,2022,10,False,True,Yes,"Kolhapur, Maharashtra"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159995,P47490,Rohan,Gupta,Female,50,1975-11-18,A-,Single,9939085441,Local Address,Nagpur,Maharashtra,India,404175,185,48,14.0,No,Occasionally,Asthma,D120,HDFC Ergo,POL666167,2023-09-08,2023,Adult,Low,2023,9,False,False,Yes,"Nagpur, Maharashtra"
159996,P112438,Suresh,Verma,Female,43,1982-02-20,A+,Married,9254467921,Local Address,Pune,Maharashtra,India,409347,185,48,14.0,Yes,No,Hypertension,D119,HDFC Ergo,POL797247,2020-07-10,2020,Adult,Low,2020,7,False,False,Yes,"Pune, Maharashtra"
159997,P128436,Vikas,Verma,Male,46,1979-06-17,B+,Single,9590932359,Local Address,Aurangabad,Maharashtra,India,407028,185,48,14.0,No,Occasionally,Hypertension,D104,Star Health,POL798028,2022-03-10,2022,Adult,Low,2022,3,False,False,Yes,"Aurangabad, Maharashtra"
159998,P36682,Amit,Mehta,Female,43,1982-05-13,A+,Single,9187837336,Local Address,Kolhapur,Maharashtra,India,402226,185,48,14.0,No,No,Unknown,D105,New India Assurance,POL693620,2022-04-15,2022,Adult,Low,2022,4,False,False,Yes,"Kolhapur, Maharashtra"
159999,P127104,Rahul,Kulkarni,Female,40,1985-03-10,AB+,Single,9616630127,Local Address,Aurangabad,Maharashtra,India,403559,185,48,14.0,Yes,No,Hypertension,D102,New India Assurance,POL269614,2023-06-19,2023,Adult,Low,2023,6,False,False,Yes,"Aurangabad, Maharashtra"

In [83]:
# Drop duplicates
df.drop_duplicates(inplace=True)

In [84]:
# Convert date
if 'Registration_Date' in df.columns:
    df['Registration_Date'] = pd.to_datetime(df['Registration_Date'], errors='coerce')
    df.sort_values(by='Registration_Date', ascending=True).head()

## 4) Filtering (Q16–35)

In [85]:
#Find all male patients 
#📝 Note: Filter rows where Gender equals "Male". 

if 'Gender' in df.columns:
    male = df[df['Gender']=='Male']

#Find all female patients above 50 years 
#📝 Note: Apply two conditions: Gender = Female AND Age > 50. 
    
    female_50 = df[(df['Gender']=='Female') & (df['Age']>50)]

In [86]:
#Find patients from Pune city 
#📝 Note: Match exact city name in City column. 

if 'City' in df.columns:
    pune = df[df['City']=='Pune']
    mumbai_pune = df[df['City'].isin(['Mumbai','Pune'])]

In [87]:
#Find patients suffering from Diabetes 
#📝 Note: Use Chronic_Condition column and filter "Diabetes". 

if 'Chronic_Condition' in df.columns:
    diabetes = df[df['Chronic_Condition']=='Diabetes']
    none_cc = df[df['Chronic_Condition']=='None']
    asthma_thyroid = df[df['Chronic_Condition'].isin(['Asthma','Thyroid'])]

In [88]:
#Find patients who are smokers 
#📝 Note: Filter Smoking_Status column for "Yes". 

if 'Smoking_Status' in df.columns:
    smokers = df[df['Smoking_Status']=='Yes']

In [89]:
#Find patients who consume alcohol occasionally 
#📝 Note: Match Alcohol_Consumption = "Occasionally". 

if 'Alcohol_Consumption' in df.columns:
    occasional = df[df['Alcohol_Consumption']=='Occasionally']

In [90]:
#Find patients with BMI greater than 30 
#📝 Note: BMI > 30 is considered obese (high risk). 

if 'BMI' in df.columns:
    obese = df[df['BMI']>30]
    underweight = df[df['BMI']<18.5]

In [91]:
#Find patients with no chronic condition 
#📝 Note: Chronic_Condition value should be "None". 

if 'Age' in df.columns:
    age_30_45 = df[(df['Age']>=30) & (df['Age']<=45)]

In [92]:
#Find patients registered after 2023 
#📝 Note: Convert Registration_Date to datetime and compare year > 2023. 

if 'Registration_Date' in df.columns:
    after_2023 = df[df['Registration_Date'].dt.year > 2023]

In [93]:
#Find patients with blood group O+ 
#📝 Note: Exact string match "O+". 

if 'Blood_Group' in df.columns:
    o_pos = df[df['Blood_Group']=='O+']

In [94]:
#Find patients insured under Star Health 
#📝 Note: Filter Insurance_Provider column. 

if 'Insurance_Provider' in df.columns:
    star = df[df['Insurance_Provider']=='Star Health']

In [95]:
#Find patients whose height is above 175 cm 
#📝 Note: Numeric filtering using Height_cm column. 

if 'Height_cm' in df.columns:
    tall = df[df['Height_cm']>175]

In [96]:
#Find patients who are married and diabetic 
#📝 Note: Marital_Status = Married AND Chronic_Condition = Diabetes. 

if 'Marital_Status' in df.columns and 'Chronic_Condition' in df.columns:
    married_diabetes = df[(df['Marital_Status']=='Married') & (df['Chronic_Condition']=='Diabetes')]

In [97]:
#Find patients who are married and diabetic 
#📝 Note: Marital_Status = Married AND Chronic_Condition = Diabetes. 

if 'Marital_Status' in df.columns and 'Chronic_Condition' in df.columns:
    married_diabetes = df[(df['Marital_Status']=='Married') & (df['Chronic_Condition']=='Diabetes')]

In [98]:
#Find patients whose email contains “gmail” 
#📝 Note: Use string methods for partial match. 

if 'Email' in df.columns:
    gmail = df[df['Email'].str.contains('gmail', case=False, na=False)]

In [99]:
#Find patients whose Patient_ID starts with “P1” 
#📝 Note: Prefix-based filtering. 

if 'Patient_ID' in df.columns:
    p1 = df[df['Patient_ID'].astype(str).str.startswith('P1')]

In [100]:
#Find patients with weight above average weight 
#📝 Note: First calculate average weight, then filter. 

if 'Weight_kg' in df.columns:
    avg_w = df['Weight_kg'].mean()
    above_avg_w = df[df['Weight_kg']>avg_w]

## 5) GroupBy (Q36–55)

In [101]:
#Find the average age of patients 
#📝 Note: Use mean aggregation on Age column. 

if 'Age' in df.columns:
    print('Avg age:', df['Age'].mean())

Avg age: 45.0293875

In [102]:
#Find average BMI by gender 
#📝 Note: Group by Gender and calculate mean BMI. 

if 'Gender' in df.columns and 'BMI' in df.columns:
    df.groupby('Gender')['BMI'].mean()

In [103]:
#Count number of patients per city 
#📝 Note: Group by City and count rows. 

if 'City' in df.columns:
    df.groupby('City').size().sort_values(ascending=False)

In [104]:
#Count number of patients per chronic condition 
#📝 Note: Shows disease distribution. 

if 'Chronic_Condition' in df.columns:
    df.groupby('Chronic_Condition').size()

In [105]:
#Find maximum age per city 
#📝 Note: Group by City and apply max on Age

if 'City' in df.columns and 'Age' in df.columns:
    df.groupby('City')['Age'].max()

In [106]:
#Find minimum BMI per gender 
#📝 Note: Identify lowest BMI per gender group. 

if 'Gender' in df.columns and 'BMI' in df.columns:
    df.groupby('Gender')['BMI'].min()

In [107]:
#Find average height per city 
#📝 Note: City-wise physical comparison. 

if 'City' in df.columns and 'Height_cm' in df.columns:
    df.groupby('City')['Height_cm'].mean()

In [108]:
#Find total patients per insurance provider 
#📝 Note: Count patients under each insurer. 

if 'Insurance_Provider' in df.columns:
    df.groupby('Insurance_Provider').size()

In [109]:
#Find average BMI per smoking status 
#📝 Note: Compare smokers vs non-smokers. 

if 'Smoking_Status' in df.columns and 'BMI' in df.columns:
    df.groupby('Smoking_Status')['BMI'].mean()

In [110]:
#Find number of patients per blood group 
#📝 Note: Useful for healthcare planning. 

if 'Blood_Group' in df.columns:
    df.groupby('Blood_Group').size()

In [111]:
#Find average age per marital status 
#📝 Note: Demographic insight. 

if 'Marital_Status' in df.columns and 'Age' in df.columns:
    df.groupby('Marital_Status')['Age'].mean()

In [112]:
#Find highest BMI per chronic condition 
#📝 Note: Identify extreme risk cases. 

if 'Chronic_Condition' in df.columns and 'BMI' in df.columns:
    df.groupby('Chronic_Condition')['BMI'].max()

In [113]:
#Find lowest weight per city 
#📝 Note: Detect outliers. 

if 'City' in df.columns and 'Weight_kg' in df.columns:
    df.groupby('City')['Weight_kg'].min()

In [114]:
#Count patients registered per year 
#📝 Note: Extract year from Registration_Date. 

if 'Registration_Date' in df.columns:
    df['Year'] = df['Registration_Date'].dt.year
    df.groupby('Year').size()

In [115]:
#Find number of patients per doctor 
#📝 Note: Doctor workload analysis. 

if 'Doctor_Name' in df.columns:
    df.groupby('Doctor_Name').size()

In [116]:
#Find average BMI per doctor 
#📝 Note: Care quality insight. 

if 'Doctor_Name' in df.columns and 'BMI' in df.columns:
    df.groupby('Doctor_Name')['BMI'].mean()

In [117]:
#Find total patients with chronic conditions 
#📝 Note: Exclude "None". 

if 'Chronic_Condition' in df.columns:
    chronic = df[df['Chronic_Condition']!='None']
    print('Total chronic:', chronic.shape[0])

Total chronic: 160000

In [118]:
#Find percentage of smokers vs non-smokers 
#📝 Note: Convert counts into percentages. 

if 'Smoking_Status' in df.columns:
    pct = df['Smoking_Status'].value_counts(normalize=True)*100
    print(pct)

Smoking_Status
No     50.0325
Yes    49.9675
Name: proportion, dtype: float64

# 6) Transformations (Q56–75)

In [119]:
# Create a new column Age_Group (Young, Adult, Senior) 
#📝 Note: 
#Age 5–25 → Young 
#Age 26–50 → Adult 
#Age Above 50 → Senior 

if 'Age' in df.columns:
    def age_group(x):
        if x<=25: return 'Young'
        elif x<=50: return 'Adult'
        else: return 'Senior'
    df['Age_Group'] = df['Age'].apply(age_group)

In [120]:
# Create a column Risk_Level based on BMI 
#📝 Note: 
#BMI < 18.5 → Low 
#BMI 18.5–25 → Normal 
#BMI 25–30 → Medium 
#BMI > 30 → High 

if 'BMI' in df.columns:
    def risk(b):
        if b<18.5: return 'Low'
        elif b<25: return 'Normal'
        elif b<30: return 'Medium'
        else: return 'High'
    df['Risk_Level'] = df['BMI'].apply(risk)

In [121]:
#Convert Registration_Date to datetime 
#📝 Note: Required before extracting year or month. 


if 'Registration_Date' in df.columns:
    df['Reg_Year'] = df['Registration_Date'].dt.year
    df['Reg_Month'] = df['Registration_Date'].dt.month

In [122]:
#Create column Is_Senior (Age > 60) 
#📝 Note: True if Age > 60, else False. 

if 'Age' in df.columns:
    df['Is_Senior'] = df['Age']>60

In [123]:
#Create column High_Risk_Patient 
#📝 Note: 
#BMI > 30 AND
#Chronic_Condition ≠ "None" 

if 'BMI' in df.columns and 'Chronic_Condition' in df.columns:
    df['High_Risk'] = (df['BMI']>30) & (df['Chronic_Condition']!='None')

In [124]:
#Convert Gender column to category type 
#📝 Note: Improves memory efficiency. 

if 'Gender' in df.columns:
    df['Gender'] = df['Gender'].astype('category')
if 'Blood_Group' in df.columns:
    df['Blood_Group'] = df['Blood_Group'].astype('category')

In [125]:
#Rename column Phone_Number to Contact_Number 
#📝 Note: Use rename operation. 

if 'Phone_Number' in df.columns:
    df.rename(columns={'Phone_Number':'Contact_Number'}, inplace=True)

In [126]:
#Drop Email column 
#📝 Note: Remove unnecessary or sensitive data. 

if 'Email' in df.columns:
    df.drop(columns=['Email'], inplace=True)

In [127]:
# Insurance status
if 'Insurance_Provider' in df.columns:
    df['Insurance_Status'] = np.where(df['Insurance_Provider']!='Unknown','Yes','No')

In [128]:
# Create column Patient_Location 
#📝 Note: Combine City and State with separator. 


if 'City' in df.columns and 'State' in df.columns:
    df['Patient_Location'] = df['City'] + ', ' + df['State']

In [129]:
#Sort patients by BMI descending 
#📝 Note: Highest BMI first. 

#Reset index after sorting 
#📝 Note: Clean index after rearranging rows. 

#Select top 10 highest BMI patients 
#📝 Note: Used for high-risk analysis. 
    

if 'BMI' in df.columns:
    df = df.sort_values(by='BMI', ascending=False)
    df = df.reset_index(drop=True)
    df.head(10)

## 7) Advanced (Q76–90)

In [130]:
#Find top 5 cities with highest average BMI 
#📝 Note: Group → Mean → Sort → Top 5. 

if 'City' in df.columns and 'BMI' in df.columns:
    df.groupby('City')['BMI'].mean().sort_values(ascending=False).head()

In [131]:
#Find bottom 5 cities with lowest average BMI 
#📝 Note: Ascending order.
    
#Find patients at high cardiovascular risk 
#📝 Note: 
#Age > 50 
#BMI > 30 
#Chronic condition present 

if 'Age' in df.columns and 'BMI' in df.columns and 'Chronic_Condition' in df.columns:
    high_risk = df[(df['Age']>50)&(df['BMI']>30)&(df['Chronic_Condition']!='None')]
    high_risk.head()

In [132]:
#Find doctor handling maximum chronic patients 
#📝 Note: Filter chronic patients, then group by doctor. 

if 'Doctor_Name' in df.columns and 'Chronic_Condition' in df.columns:
    df[df['Chronic_Condition']!='None'].groupby('Doctor_Name').size().sort_values(ascending=False)

In [133]:
#Find insurance provider covering most senior citizens 
#📝 Note: Senior = Age > 60. 

if 'Age' in df.columns and 'Insurance_Provider' in df.columns:
    df[df['Age']>60].groupby('Insurance_Provider').size().sort_values(ascending=False)

In [134]:
#Find patients eligible for lifestyle counseling 
#📝 Note: BMI > 25 OR Smoking = Yes OR Alcohol = Occasionally. 

if 'Smoking_Status' in df.columns and 'Alcohol_Consumption' in df.columns and 'BMI' in df.columns:
    lifestyle = df[(df['BMI']>25)|(df['Smoking_Status']=='Yes')|(df['Alcohol_Consumption']=='Occasionally')]
    lifestyle.head()

In [135]:
#Identify potential ICU-risk patients 
#📝 Note: Age > 65 AND BMI > 30 AND chronic condition present. 

if 'Age' in df.columns and 'BMI' in df.columns and 'Chronic_Condition' in df.columns:
    icu = df[(df['Age']>65)&(df['BMI']>30)&(df['Chronic_Condition']!='None')]
    icu.head()

In [136]:
#Find correlation between Age and BMI 
#📝 Note: Measures relationship strength. 

if 'Age' in df.columns and 'BMI' in df.columns:
    print(df[['Age','BMI']].corr())

          Age       BMI
Age  1.000000 -0.001196
BMI -0.001196  1.000000

In [137]:
#Export cleaned DataFrame to CSV 
#📝 Note: Final output after transformations. 

df.to_csv('final_healthcare_cleaned.csv', index=False)